{% set name = "pybtexris" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybtexris-{{ version }}.tar.gz
  sha256: 84ce8d59e2934d8c5416fe2cc6d57c2fbf3d8ab0c330dcb2103b687491158ebd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pybtex >=0.24.0,<0.25.0

test:
  imports:
    - pybtexris
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rbturnbull/pybtexris
  summary: A pybtex plugin for working with RIS files.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rbturnbull
    - vinisalazar
